---
- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - "python3-debian"

- name: Remove old kea apt configuration
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/apt/sources.list.d/kea.list"
    - "/etc/apt/keyrings/kea.gpg"

- name: Add kea apt repository
  ansible.builtin.deb822_repository:
    name: kea
    uris: "{{ kea_apt_repo_url }}"
    suites: "{{ kea_apt_repo_suite }}"
    components: "{{ kea_apt_repo_component }}"
    signed_by: "{{ kea_apt_repo_gpg_key }}"
    state: present
  register: _apt_repo

- name: Install extra kea packages
  ansible.builtin.apt:
    name: "{{ kea_packages }}"
    update_cache: "{{ true if _apt_repo is changed else false }}"
    state: present
